### ISSUE TITLE
Add field(s) representing DNS header flags

### ISSUE THREAD

**Issue by neilcook** [PowerDNS/dnsmessage#9]
There are various DNS flags that are not represented in the protobuf dnsmessage. For example Recursion Desired (RD), Recursion Available (RA), Truncated Response (TC) etc.

It would be good if these were available in the protobuf in some form, specifically:

AA, RD, RA, TC, AD, CD (from regular DNS header flags)

And also it would be nice if the protobuf indicated:
- The EDNS0 version number (if applicable)
- Any EDNS0 header flags, i.e. DO

**Comment by omoerbeek** [comment]
Currently we add nothing to `Meta` in rec. We could reserve a portion of the namespace for rec itself, e.g. any name starting with underscore of some other prefix. Then properly document the fields rec adds by itself.

**Comment by neilcook** [comment]
I think dnsdist could also potentially add these fields?

**Comment by omoerbeek** [comment]
yes, configurable in `RemoteLogAction` and `RemoteLogResponseAction`. So specific  product name should likely not be part of the reserved prefix. We still want to coordinate things between rec and dnsdist (if dnsdist is also going to be adding Meta values as well by its own).

**Comment by omoerbeek** [comment]
@rgacogne If you agree with the general idea, I'll make an explicit proposal for approach 2.

**Comment by rgacogne** [comment]
Sounds good to me!

**Comment by omoerbeek** [comment]
https://github.com/omoerbeek/pdns/tree/rec-add-pb-edns-hdr has a wip branch. This seems all to be doable, albeit a bit tricky (when naming things, the current code doesn't not really distinguish between the question and answer header, so they are easily mixed up. 

Also, the edns parsing code has a subtle thing going: it skips zero sized option records. This is suitable for scanning for a ECS, but not if we want to have the TTL fields always.

This adding of meta info need to be controled by a flag as well I suppose.

Anyway, I'll add test and make this a proper PR if there is consensus this is the way to go.

**Comment by omoerbeek** [comment]
```
[2024-11-12 15:00:00.974306] Query of size 31: 127.0.0.1:52518 (N/A) -> 127.0.0.1:5301 (UDP) id: 64896 uuid: b'f5370f4f80cd47c986f8f6f7655f947b' requestorid: N/A deviceid: N/A devicename: N/A serverid: b'mbp.local' nod: N/A workerId: 2 pcCacheHit: N/A outgoingQueries: N/A
- (meta) _pdnsQFlags -> 288
- Question: 1, 1, www.drijf.net.
[2024-11-12 15:00:00.974402] Response of size 47: 127.0.0.1:52518 (N/A) -> 127.0.0.1:5301 (UDP) id: 64896 uuid: b'f5370f4f80cd47c986f8f6f7655f947b' requestorid: N/A deviceid: N/A devicename: N/A serverid: b'mbp.local' nod: N/A workerId: 2 pcCacheHit: False outgoingQueries: 0
- (meta) _pdnsRFlags -> 33184
- Question: 1, 1, www.drijf.net.
- Query time: 2024-11-12 15:00:00.974295
- Response Code: 0, RRs: 1
         - 1, 1, www.drijf.net., 3181, 46.23.93.236, False
```

**Comment by neilcook** [comment]
That would also be fine for me, I don't mind either way.

**Comment by rgacogne** [comment]
So two new optional fields in `PBDNSMessage` directly, I guess? That would make sense to me as well.

**Comment by omoerbeek** [comment]
> So two new optional fields in `PBDNSMessage` directly, I guess? That would make sense to me as well.

Actually four fields: two fields for the question, two for answer part. I'll prep a PR for dnsmessage.proto

**Comment by rgacogne** [comment]
Hmm, I guess that's because you want the headers of the query showing up in the response protobuf as well?

**Comment by rgacogne** [comment]
It depends on what Neil needs exactly, but just so you know I don't think dnsdist will be able to fill the query headers in the response protobuf message. We only keep this information around:
- initial query ID
- initial flags (16 bits)
- whether the DNSSEC OK bit set was set

At the moment we don't know anything else about the query when we receive the response. We also don't part the EDNS version, rcode, etc at the moment but I guess we could.

**Comment by omoerbeek** [comment]
OK. That makes the case clear I think.
